"""initial schema

Revision ID: f8fca2e8098e
Revises: 
Create Date: 2026-07-21 18:16:18.193344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8fca2e8098e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('frames_processed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('avg_attention', sa.Float(), nullable=False),
    sa.Column('students_present', sa.Integer(), nullable=False),
    sa.Column('phones_visible', sa.Integer(), nullable=False),
    sa.Column('hands_raised', sa.Integer(), nullable=False),
    sa.Column('low_attention_alert', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_snapshots_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_snapshots_session_ts', ['session_id', 'timestamp'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('first_seen_ts', sa.Float(), nullable=False),
    sa.Column('last_seen_ts', sa.Float(), nullable=False),
    sa.Column('frames_seen', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_students_session_track', ['session_id', 'track_id'], unique=True)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('first_seen_ts', sa.Float(), nullable=False),
    sa.Column('last_seen_ts', sa.Float(), nullable=False),
    sa.Column('presence_ratio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_session', ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_session_id'), ['session_id'], unique=False)

    op.create_table('frame_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('bbox_x2', sa.Float(), nullable=False),
    sa.Column('bbox_y2', sa.Float(), nullable=False),
    sa.Column('head_pose', sa.String(length=10), nullable=False),
    sa.Column('yaw', sa.Float(), nullable=False),
    sa.Column('pitch', sa.Float(), nullable=False),
    sa.Column('roll', sa.Float(), nullable=False),
    sa.Column('ear', sa.Float(), nullable=False),
    sa.Column('eyes_closed', sa.Boolean(), nullable=False),
    sa.Column('blink_total', sa.Integer(), nullable=False),
    sa.Column('blink_rate', sa.Float(), nullable=False),
    sa.Column('gaze', sa.String(length=10), nullable=False),
    sa.Column('phone_visible', sa.Boolean(), nullable=False),
    sa.Column('looking_at_phone', sa.Boolean(), nullable=False),
    sa.Column('hand_raised', sa.Boolean(), nullable=False),
    sa.Column('attention_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frame_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frame_analysis_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_frame_analysis_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ix_frames_session_ts', ['session_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame_analysis', schema=None) as batch_op:
        batch_op.drop_index('ix_frames_session_ts')
        batch_op.drop_index(batch_op.f('ix_frame_analysis_student_id'))
        batch_op.drop_index(batch_op.f('ix_frame_analysis_session_id'))

    op.drop_table('frame_analysis')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_session_id'))
        batch_op.drop_index('ix_attendance_session')

    op.drop_table('attendance')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index('ix_students_session_track')
        batch_op.drop_index(batch_op.f('ix_students_session_id'))

    op.drop_table('students')
    with op.batch_alter_table('class_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_session_ts')
        batch_op.drop_index(batch_op.f('ix_class_snapshots_session_id'))

    op.drop_table('class_snapshots')
    op.drop_table('sessions')
    # ### end Alembic commands ###
